<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!--The logo was created on design.com https://www.design.com/maker/logo/elegant-rectangle-letter-n-576322?text=Nexus&isVariation=True&searchImpressionId=e57eb4fd-9f14-4905-9944-216dc884006b -->
    <meta name="description" content="Nexus - A global leader in IT solutions, offering innovative technology services like AI, cloud computing, and cybersecurity.">
    <meta name="keywords" content="Nexus, IT solutions, technology, AI, cloud computing, cybersecurity, software development">
    <title>Welcome to Nexus</title>
    <link rel="stylesheet" href="style/styles.css">
    <link rel="icon" href="images/logo.png" type="image/png" class="bgimg">
</head>
<body>
    <header>
        <a href="index.html">
            <img src="images/logo.png" alt="Nexus Logo" class="logo">
        </a>
        <h1>Welcome to Nexus</h1>
        <p>Our future starts here</p>
    </header>
    <nav>
        <def class="nav-link">
            <ul>
                <li><a href="index.html" class="nav-link"><strong>Home</strong></a></li>
                <li><a href="jobs.html" class="nav-link"><strong>Job Opportunities</strong></a></li>
                <li><a href="apply.html" class="nav-link"><strong>Apply Now</strong></a></li>
                <li><a href="about.html" class="nav-link"><strong>About Us</strong></a></li>
            </ul>
        </def>
    </nav>