<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Nexus - A global leader in IT solutions, offering innovative technology services like AI, cloud computing, and cybersecurity.">
    <meta name="keywords" content="Nexus, IT solutions, technology, AI, cloud computing, cybersecurity, software development">
    <link rel="stylesheet" href="style/styles.css">
    <link rel="icon" href="images/logo.png" type="image/png" class="bgimg">
</head>
<body>
    <header>
        <a href="index.html">
            <img src="images/logo.png" alt="Nexus Logo" class="logo">
        </a>
        <h1>Welcome to Nexus</h1>
        <p>Our future starts here</p>
    </header>