    <nav>
        <def class="nav-link">
            <ul>
                <li><a href="index.php" class="nav-link"><strong>Home</strong></a></li>
                <li><a href="jobs.php" class="nav-link"><strong>Job Opportunities</strong></a></li>
                <li><a href="apply.php" class="nav-link"><strong>Apply Now</strong></a></li>
                <li><a href="about.php" class="nav-link"><strong>About Nexus</strong></a></li>
            </ul>
        </def>
    </nav>